spring.application.name=MVCProj2-WishMessageApp

#viewResolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

##Embedded Server port Numbersssssss
#server.port=4041
#
##context path
#server.servlet.context-path=/WishApp