spring.application.name=MVCProj-7RequestParamFormsDataBinding

#InternalViewResolver Configuration
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp


#Standalone apps context-paths
server.servlet.context-path=/MVC-HtmlForms 
#Embedded Server Port No
server.port=4041